apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ .Release.Name }}-redis
      labels:
        app: {{ .Chart.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: database
    data:
      redis.conf: |
        {{ range $key, $value := .Values.config -}}
        {{ $key }} {{ $value }}
        {{ end }}
      dictator.json: |
        {
          "svc_name": "{{ .Release.Name }}",
          "log_level": "{{ .Values.dictator.log_level | default "INFO" }}",
          "http_port": {{ .Values.dictator.port }},
          "node": {
            "name": "localhost",
            "host": "127.0.0.1",
            "port": 6379,
            "loading_timeout": {{ .Values.dictator.loading_timeout }}
          },
          "master_service": "{{ .Release.Name }}"
        }
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ .Release.Name }}-probes
      labels:
        app: {{ .Chart.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: database
    data:
      liveness-probe.sh: |-
        #!/bin/bash
        redis-cli ping
      readiness-probe.sh: |-
        #!/bin/bash
        redis-cli ping
